/* eslint-disable space-before-function-paren */
/* eslint-disable no-multi-spaces */
/* eslint-disable semi */
/* eslint-disable no-undef */
/* eslint-disable indent */
/* eslint-disable quotes */
import './assets/main.css'
import { createApp } from 'vue'
import App from './App.vue'
import router from './router'
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import store from './store'
import './assets/styles/github-markdown.css'
import './assets/styles/github-highlight.css'
import './assets/styles/dark-theme.css'
import {
  faHouse,
  faBlog,
  faMagnifyingGlass,
  faQuestion,
  faDiagramProject,
  faFlask,
  faPenToSquare,
  faComment,
  faCommentSlash,
  faRightToBracket,
  faRegistered,
  faArrowRotateBack,
  faEllipsis,
  faBoxOpen,
  faDice,
  faHeading,
  faList,
  faPaperPlane,
  faFilm,
  faBars,
  faBookmark,
  faCheckCircle,
  faBold,
  faItalic,
  faCode,
  faFileCode,
  faQuoteLeft,
  faTrash,
  faCalendar,
  faEye,
  faEyeSlash,
  faCommentDots,
  faImage,
  faEdit,
  faHome,
  faArrowLeft,
  faSyncAlt,
  faReply,
  faClock,
  faImages,
  faSun,
  faMoon,
  faShare,
  faArchive,
  faRss,
  faArrowUp,
  faFire,
  faTag,
  faLightbulb,
  faTimes,
  faBolt,
  faBookOpen,
  faChevronLeft,
  faChevronRight,
  faStrikethrough,
  faListUl,
  faListOl,
  faMinus,
  faTable,
  faLink,
  faHeart,
  faExclamationTriangle,
  faRedo,
  faUpload,
  faGear,
  faLocationDot,
  faNewspaper,
  faExternalLinkAlt,
  faGlobe,
  faBook,
  faDownload,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faStar,
  faCog,
  faUser,
  faInfoCircle,
  faWarning,
  faTimesCircle,
  faCheckCircle as faCheckCircleAlt,
  faQuestionCircle,
  faAddressBook,
  faVideo,
  faVolumeUp,
  faFile,
  faFolder,
  faTerminal,
  faDatabase,
  faServer,
  faCloud,
  faChalkboard,
  faCloudUploadAlt,
  faFilePowerpoint
} from '@fortawesome/free-solid-svg-icons'

import {
  faGithub,
  faGitlab,
  faBitbucket,
  faWeixin,
  faWeibo,
  faQq,
  faBilibili,
  faYoutube,
  faTwitter,
  faFacebook,
  faInstagram,
  faLinkedin,
  faGit
} from '@fortawesome/free-brands-svg-icons'

library.add(
  faHouse,
  faBlog,
  faMagnifyingGlass,
  faQuestion,
  faDiagramProject,
  faFlask,
  faPenToSquare,
  faComment,
  faCommentSlash,
  faRightToBracket,
  faRegistered,
  faArrowRotateBack,
  faEllipsis,
  faBoxOpen,
  faDice,
  faHeading,
  faList,
  faPaperPlane,
  faFilm,
  faBars,
  faBookmark,
  faCheckCircle,
  faBold,
  faItalic,
  faCode,
  faFileCode,
  faQuoteLeft,
  faTrash,
  faCalendar,
  faEye,
  faEyeSlash,
  faCommentDots,
  faImage,
  faEdit,
  faHome,
  faArrowLeft,
  faSyncAlt,
  faReply,
  faClock,
  faImages,
  faSun,
  faMoon,
  faShare,
  faArchive,
  faRss,
  faArrowUp,
  faFire,
  faTag,
  faLightbulb,
  faTimes,
  faBolt,
  faBookOpen,
  faChevronLeft,
  faChevronRight,
  faStrikethrough,
  faListUl,
  faListOl,
  faMinus,
  faTable,
  faLink,
  faHeart,
  faExclamationTriangle,
  faRedo,
  faUpload,
  faGear,
  faLocationDot,
  faNewspaper,
  faExternalLinkAlt,
  faGlobe,
  faBook,
  faDownload,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faStar,
  faCog,
  faUser,
  faInfoCircle,
  faWarning,
  faTimesCircle,
  faCheckCircleAlt,
  faQuestionCircle,
  faAddressBook,
  faVideo,
  faVolumeUp,
  faFile,
  faFolder,
  faTerminal,
  faDatabase,
  faServer,
  faCloud,
  faChalkboard,
  faCloudUploadAlt,
  faFilePowerpoint,
  faGithub,
  faGitlab,
  faBitbucket,
  faWeixin,
  faWeibo,
  faQq,
  faBilibili,
  faYoutube,
  faTwitter,
  faFacebook,
  faInstagram,
  faLinkedin,
  faGit
)

const app = createApp(App)
app.use(router)
app.use(store)
app.component('FontAwesomeIcon', FontAwesomeIcon)
app.mount('#app')
